CHOICES_BUILDERS = (
    ('other', 'Other'),
    ('seafarer yachts', 'Seafarer Yachts'),
    ('fairey marine ltd', 'Fairey Marine Ltd'),
    ('c&c yachts', 'C&C Yachts'),
    ('ta shing yacht building ltd.', 'Ta Shing Yacht Building Ltd.'),
    ('sabre yachts (usa)', 'Sabre Yachts (USA)'),
    ('catalina yachts', 'Catalina Yachts'),
    ('pearson yachts', 'Pearson Yachts'),
    ('bristol yachts', 'Bristol Yachts'),
    ('american mariner industries', 'American Mariner Industries'),
    ('hughes boat works', 'Hughes Boat Works'),
    ('coronado yachts', 'Coronado Yachts'),
    ('taswell yachts', 'Taswell Yachts'),
    ('allied boat company inc. (usa)', 'Allied Boat Company Inc. (USA)'),
    ('chrysler marine', 'Chrysler Marine'),
    ('columbia yachts', 'Columbia Yachts'),
    ('kenner boat company', 'Kenner Boat Company'),
    ('grampian marine', 'Grampian Marine'),
    ('islander / tradewind yachts', 'Islander / Tradewind Yachts'),
    ('american fiberglass corp.', 'American Fiberglass Corp.'),
    ('endeavour yacht corp.', 'Endeavour Yacht Corp.'),
    ('mirage yachts ltd (can)', 'Mirage Yachts Ltd (CAN)'),
    ('brjesson brothers', 'Brjesson Brothers'),
    ('paceship yachts ltd.', 'Paceship Yachts Ltd.'),
    ('blue bouy yacht co.', 'Blue Bouy Yacht Co.'),
    ('owens yacht company', 'Owens Yacht Company'),
    ('precision boat works', 'Precision Boat Works'),
    ('clark boat company', 'Clark Boat Company'),
    ('topper international', 'Topper International'),
    ('cape cod shipbuilding', 'Cape Cod Shipbuilding'),
    ('jensen marine/cal boats', 'Jensen Marine/Cal Boats'),
    ('leisure yachts', 'Leisure Yachts'),
    ('schock w.d.', 'Schock W.D.'),
    ('hallberg-rassy', 'Hallberg-Rassy'),
    ('alden yachts (usa)', 'Alden Yachts (USA)'),
    ('south coast seacraft co.', 'South Coast Seacraft Co.'),
    ('comar yachts', 'Comar Yachts'),
    ('sunbeam yachts - schchl yachtbau', 'Sunbeam Yachts - Schchl Yachtbau'),
    ('beneteau usa', 'Beneteau USA'),
    ('westerly marine construction ltd.', 'Westerly Marine Construction Ltd.'),
    ('hinckley yachts', 'Hinckley Yachts'),
    ('jeanneau (fra)', 'Jeanneau (FRA)'),
    ('ranger yachts (usa)', 'Ranger Yachts (USA)'),
    ('wauquiez, henri (chantier)', 'Wauquiez, Henri (Chantier)'),
    ("o'day corp.", "O'Day Corp."),
    ('hunter marine (usa)', 'Hunter Marine (USA)'),
    ('sydney yachts/bashford int.', 'Sydney Yachts/Bashford Int.'),
    ('j boats', 'J Boats'),
    ('dehler yachts', 'Dehler Yachts'),
    ('tanzer industries ltd.', 'Tanzer Industries Ltd.'),
    ('abbott boats inc.', 'Abbott Boats Inc.'),
    ('kettenburg boats', 'Kettenburg Boats'),
    ('elan yachts (slo)', 'Elan Yachts (SLO)'),
    ('buchan boat co.', 'Buchan Boat Co.'),
    ('latitude 46 (fra)', 'Latitude 46 (FRA)'),
    ('cascade yachts/yacht constructors, inc.', 'Cascade Yachts/Yacht Constructors, Inc.'),
    ('alubat (fra)', 'Alubat (FRA)'),
    ('lecomte yachts', 'LeComte Yachts'),
    ('gulf coast sailboats', 'Gulf Coast Sailboats'),
    ('hurley marine ltd.', 'Hurley Marine Ltd.'),
    ('sadler yachts', 'Sadler Yachts'),
    ('bianca yachts', 'Bianca Yachts'),
    ('trintella yachts', 'Trintella Yachts'),
    ('halmatic', 'Halmatic'),
    ('russell marine ltd.', 'Russell Marine Ltd.'),
    ('hinterhoeller yachts ltd.', 'Hinterhoeller Yachts Ltd.'),
    ('melges performance sailboats', 'Melges Performance Sailboats'),
    ('ericson yachts (usa)', 'Ericson Yachts (USA)'),
    ('cape dory yachts', 'Cape Dory Yachts'),
    ('prout & sons', 'Prout & Sons'),
    ('endeavour catamaran corp.', 'Endeavour Catamaran Corp.'),
    ('luger industries (usa)', 'Luger Industries (USA)'),
    ('beneteau', 'Beneteau'),
    ('morgan yachts', 'Morgan Yachts'),
    ('irwin yachts', 'Irwin Yachts'),
    ('lawley (george lawley & son)', 'Lawley (George Lawley & Son)'),
    ('olympic marine (greece)', 'Olympic Marine (GREECE)'),
    ('marieholm boats (swe)', 'Marieholm Boats (SWE)'),
    ('tylercraft (usa)', 'Tylercraft (USA)'),
    ('trapper yachts (uk)', 'Trapper Yachts (UK)'),
    ('anstey yachts ltd. (uk)', 'Anstey Yachts Ltd. (UK)'),
    ('caliber yachts (usa)', 'Caliber Yachts (USA)'),
    ('dickerson boatbuilders (usa)', 'Dickerson Boatbuilders (USA)'),
    ('antigua yachts (usa)', 'Antigua Yachts (USA)'),
    ('cs yachts (canadian sailcraft)', 'CS Yachts (Canadian Sailcraft)'),
    ('dufour yachts (fra)', 'Dufour Yachts (FRA)'),
    ('cheoy lee shipyard', 'Cheoy Lee Shipyard'),
    ('camper & nicholson', 'Camper & Nicholson'),
    ('moody yachts (a. h. moody & sons)', 'Moody Yachts (A. H. Moody & Sons)'),
    ('lancer yacht corp. (usa)', 'Lancer Yacht Corp. (USA)'),
    ('ray greene & co.', 'Ray Greene & Co.'),
    ('lippincott boat works (usa)', 'Lippincott Boat Works (USA)'),
    ('fountaine pajot', 'Fountaine Pajot'),
    ('pdq yachts (can)', 'PDQ Yachts (CAN)'),
    ('baltic yachts', 'Baltic Yachts'),
    ('nautor (swan sailboats)', 'Nautor (Swan sailboats)'),
    ('alcort (usa)', 'Alcort (USA)'),
    ('ultimate sailboats', 'Ultimate Sailboats'),
    ('nye yachts (can)', 'Nye Yachts (CAN)'),
    ('reinell boat works', 'Reinell Boat Works'),
    ('westfield engineering co. (marine) ltd.', 'Westfield Engineering Co. (Marine) Ltd.'),
    ('macwester marine co. ltd. (uk)', 'Macwester Marine Co. Ltd. (UK)'),
    ('yachting france (fra)', 'Yachting France (FRA)'),
    ('nickels boat works, inc. (usa)', 'Nickels Boat Works, Inc. (USA)'),
    ('ticon yachts ltd.', 'Ticon Yachts Ltd.'),
    ('marine', 'Marine'),
    ('cnso (constructions nautiques du sud-ouest)', 'CNSO (Constructions Nautiques du Sud-Ouest)'),
    ('bavaria yachts (ger)', 'Bavaria Yachts (GER)'),
    ('bayliner (buccaneer/us yachts)', 'Bayliner (Buccaneer/US Yachts)'),
    ('uniflite inc. (usa)', 'Uniflite Inc. (USA)'),
    ('yankee yachts inc. (usa)', 'Yankee Yachts Inc. (USA)'),
    ('ggeri', 'ggeri'),
    ('scanmar yachts', 'Scanmar Yachts'),
    ('performance cruising', 'Performance Cruising'),
    ('shannon yachts', 'Shannon Yachts'),
    ('alpa yachts (ita)', 'Alpa Yachts (ITA)'),
    ('stuart marine', 'Stuart Marine'),
    ('seidelmann yachts', 'Seidelmann Yachts'),
    ('dencho marine', 'Dencho Marine'),
    ('island packet yachts', 'Island Packet Yachts'),
    ('roughwater boats', 'Roughwater Boats'),
    ('alo yachts (nor)', 'Alo Yachts (NOR)'),
    ('ta chiao (taiwan)', 'Ta Chiao (TAIWAN)'),
    ('edel (fra)', 'Edel (FRA)'),
    ('hobie cat', 'Hobie Cat'),
    ('belliure yachts', 'Belliure Yachts'),
    ('sweden yachts', 'Sweden Yachts'),
    ('boat works ltd. (can)', 'Boat Works Ltd. (CAN)'),
    ('marine concepts (usa)', 'Marine Concepts (USA)'),
    ('cabo rico (cr)', 'Cabo Rico (CR)'),
    ('marshall marine corp.', 'Marshall Marine Corp.'),
    ('international marine (usa)', 'International Marine (USA)'),
    ('quincy adams yacht yard', 'Quincy Adams Yacht Yard'),
    ('albin marine', 'Albin Marine'),
    ('s2 yachts (usa)', 'S2 Yachts (USA)'),
    ('watkins yachts', 'Watkins Yachts'),
    ('nevins inc.', 'Nevins Inc.'),
    ('wibo yachts', 'Wibo Yachts'),
    ('north wind yachts (esp)', 'North Wind Yachts (ESP)'),
    ('amel (chantier)', 'Amel (Chantier)'),
    ('kong & halvorsen marine & engineering', 'Kong & Halvorsen Marine & Engineering'),
    ('northshore yachts (uk)', 'Northshore Yachts (UK)'),
    ('com-pac yachts', 'Com-Pac Yachts'),
    ('dart sailboats', 'Dart Sailboats'),
    ('wiggers custom yachts ltd.', 'Wiggers Custom Yachts Ltd.'),
    ('mcvay fiberglass yachts', 'McVay Fiberglass Yachts'),
    ('mount desert yacht yard', 'Mount Desert Yacht Yard'),
    ('tartan marine', 'Tartan Marine'),
    ('douglass & mcleod', 'Douglass & McLeod'),
    ('capital yachts corp.', 'Capital Yachts Corp.'),
    ('ouyang boat works (can)', 'Ouyang Boat Works (CAN)'),
    ('privilege catamarans', 'Privilege Catamarans'),
    ('allen boat co. (usa)', 'Allen Boat Co. (USA)'),
    ('mader bootswerft', 'Mader Bootswerft'),
    ('contest yachts - conyplex', 'Contest Yachts - Conyplex'),
    ('hunter boats ltd.', 'Hunter Boats Ltd.'),
    ('quorning boats', 'Quorning Boats'),
    ('hanse yachts', 'Hanse Yachts'),
    ('coastal recreation inc.', 'Coastal Recreation Inc.'),
    ('jeremy rogers ltd.', 'Jeremy Rogers Ltd.'),
    ('csy (caribbean sailing yachts)', 'CSY (Caribbean Sailing Yachts)'),
    ('carroll marine', 'Carroll Marine'),
    ('barberis (cantieri)', 'Barberis (Cantieri)'),
    ('thames marine (uk)', 'Thames Marine (UK)'),
    ('gavia yachts', 'Gavia Yachts'),
    ('tyler boat co. ltd. (uk)', 'Tyler Boat Co. Ltd. (UK)'),
    ('anne wever shipyard (nl)', 'Anne Wever Shipyard (NL)'),
    ('challenger yachts corp.', 'Challenger Yachts Corp.'),
    ('yachts a/s', 'Yachts A/S'),
    ('luffe yachts (den)', 'Luffe Yachts (DEN)'),
    ('laguna yachts', 'Laguna Yachts'),
    ('macgregor yacht corp', 'Macgregor Yacht Corp'),
    ('tpi composites', 'TPI Composites'),
    ('parker yachts (uk)', 'Parker Yachts (UK)'),
    ('herreshoff mfg. co.', 'Herreshoff Mfg. Co.'),
    ('santa cruz yachts', 'Santa Cruz Yachts'),
    ('sovereign yachts (custom fiberglass products)', 'Sovereign Yachts (Custom Fiberglass Products)'),
    ('soverel marine', 'Soverel Marine'),
    ('nauticat - siltala yachts', 'Nauticat - Siltala Yachts'),
    ('winga marin', 'Winga Marin'),
    ('wasa yachts', 'Wasa Yachts'),
    ('chris-craft', 'Chris-Craft'),
    ('lillia (cantiere nautico lillia)', 'Lillia (Cantiere Nautico Lillia)'),
    ('folli boats (lariovela s.n.c.)', 'Folli Boats (LARIOVELA s.n.c.)'),
    ('helmsman yachts', 'Helmsman Yachts'),
    ('mallard (chantier mallard)', 'Mallard (Chantier Mallard)'),
    ('corsair marine', 'Corsair Marine'),
    ('pacific seacraft', 'Pacific Seacraft'),
    ('colvic craft', 'Colvic Craft'),
    ("gib'sea/gibert marine (fra)", "Gib'sea/Gibert Marine (FRA)"),
    ('ontario yachts', 'Ontario Yachts'),
    ('aloa marine (fra)', 'Aloa Marine (FRA)'),
    ('yamaha', 'Yamaha'),
    ('mal yachts (swe)', 'Mal Yachts (SWE)'),
    ('fabola boats (swe)', 'Fabola Boats (SWE)'),
    ('gulfstar yachts', 'Gulfstar Yachts'),
    ('comfortbtar ab', 'Comfortbtar AB'),
    ('helms - jack a. helms co.', 'Helms - Jack A. Helms Co.'),
    ('jonmeri yachts', 'Jonmeri Yachts'),
    ('maestro boats (fin)', 'Maestro Boats (FIN)'),
    ('finngulf yachts', 'Finngulf Yachts'),
    ('gozzard yachts (north castle marine ltd.)', 'Gozzard Yachts (North Castle Marine Ltd.)'),
    ('grand soleil (cantiere del pardo)', 'Grand Soleil (Cantiere del Pardo)'),
    ('queen long marine', 'Queen Long Marine'),
    ('jongert', 'Jongert'),
    ('najad yachts (swe)', 'Najad Yachts (SWE)'),
    ('passport yachts', 'Passport Yachts'),
    ('saga marine', 'Saga Marine'),
    ('archambault boats (fra)', 'Archambault Boats (FRA)'),
    ('hake yachts (seaward)', 'Hake Yachts (Seaward)'),
    ('abeking & rasmussen', 'Abeking & Rasmussen'),
    ('south hants engineering', 'South Hants Engineering'),
    ('vindo (ntesund varv ab)', 'Vindo (Ntesund Varv AB)'),
    ('freedom yachts', 'Freedom Yachts'),
    ('catalac / tom lack catamarans', 'Catalac / Tom Lack Catamarans'),
    ('scepter yachts ltd. (can)', 'Scepter Yachts Ltd. (CAN)'),
    ('calgan marine ltd. (can)', 'Calgan Marine Ltd. (CAN)'),
    ('x-yachts', 'X-Yachts'),
    ('pogo structures', 'POGO Structures'),
    ('rustler yachts ltd.', 'Rustler Yachts Ltd.'),
    ('ta yang yacht building co. ltd.', 'Ta Yang Yacht Building Co. Ltd.'),
    ('graves yacht yard (usa)', 'Graves Yacht Yard (USA)'),
    ('alsberg brothers boatworks', 'Alsberg Brothers Boatworks'),
    ('rocket boats', 'Rocket Boats'),
    ('pacific boat works', 'Pacific Boat Works'),
    ('deacons boat yard ltd.', 'Deacons Boat Yard Ltd.'),
    ('cherubini yachts', 'Cherubini Yachts'),
    ('mcdell marine (nz)', 'McDell Marine (NZ)'),
    ('oyster marine', 'Oyster Marine'),
    ('aquafibre ltd.', 'Aquafibre Ltd.'),
    ('sylvana yachts inc.', 'Sylvana Yachts Inc.'),
    ('eastsail yachts', 'Eastsail Yachts'),
    ('aquarius sail inc.', 'Aquarius Sail Inc.'),
    ('knutson shipbuilding corp.', 'Knutson Shipbuilding Corp.'),
    ('avance yachts', 'Avance Yachts'),
    ('hylas yachts usa', 'Hylas Yachts USA'),
    ('amigo yachts (swe)', 'Amigo Yachts (SWE)'),
    ('c. e. ryder', 'C. E. Ryder'),
    ('spencer boats ltd.', 'Spencer Boats Ltd.'),
    ('john baker ltd.', 'John Baker Ltd.'),
    ('rondar raceboats', 'Rondar Raceboats'),
    ('allmand boats inc.(usa)', 'Allmand Boats Inc.(USA)'),
    ('marine construction ltd. (uk)', 'Marine Construction Ltd. (UK)'),
    ('aerodyne yachts ltd.', 'Aerodyne Yachts Ltd.'),
    ('cooper yachts ltd. (can)', 'Cooper Yachts Ltd. (CAN)'),
    ('kirie (fra)', 'Kirie (FRA)'),
    ('yachtsmiths international inc.', 'Yachtsmiths International Inc.'),
    ('bayfield boat yard ltd. (can)', 'Bayfield Boat Yard Ltd. (CAN)'),
    ('ds yachts (schwill yachts) (can)', 'DS Yachts (Schwill Yachts) (CAN)'),
    ('dyer boats', 'Dyer Boats'),
    ('mfg boat company (usa)', 'MFG Boat Company (USA)'),
    ('outremer (atelier outremer)', 'Outremer (Atelier Outremer)'),
    ('haines hunter', 'Haines Hunter'),
    ('aubin (chantier aubin)', 'Aubin (Chantier Aubin)'),
    ('sudplast (bwc illmensee)', 'SUDPLAST (BWC Illmensee)'),
    ('clipper marine', 'Clipper Marine'),
    ('amsterdam shipyard g. de vries lentsch', 'Amsterdam Shipyard G. de Vries Lentsch'),
    ('new orleans marine', 'New Orleans Marine'),
    ('peter webster ltd.', 'Peter Webster Ltd.'),
    ('sailcraft ltd. (uk)', 'Sailcraft Ltd. (UK)'),
    ('zuanelli (cantiere zuanelli)', 'Zuanelli (Cantiere Zuanelli)'),
    ('bell woodworking ltd. (uk)', 'Bell Woodworking Ltd. (UK)'),
    ('seamaster ltd. (uk)', 'Seamaster Ltd. (UK)'),
    ('weeks yacht yard (usa)', 'Weeks Yacht Yard (USA)'),
    ('bandholm yachts', 'Bandholm Yachts'),
    ("nor'sea marine (usa)", "Nor'Sea Marine (USA)"),
    ('montgomery marine products', 'Montgomery Marine Products'),
    ('mackay boats ltd.', 'MacKay Boats Ltd.'),
    ('plastiglass co.', 'PlastiGlass Co.'),
    ('plastrend / composite technologies', 'Plastrend / Composite Technologies'),
    ('puma yachts (nao-glass)(esp)', 'Puma Yachts (Nao-Glass)(ESP)'),
    ('etap yachting', 'Etap Yachting'),
    ('formula yachts (usa)', 'Formula Yachts (USA)'),
    ('goetz custom sailboats (usa)', 'Goetz Custom Sailboats (USA)'),
    ('ovington boats ltd.', 'Ovington Boats Ltd.'),
    ('morris yachts', 'Morris Yachts'),
    ('butler boats', 'Butler Boats'),
    ('compass yachts ltd. (australia/nz)', 'Compass Yachts Ltd. (Australia/NZ)'),
    ('cavalier yachts', 'Cavalier Yachts'),
    ('luke, paul e.', 'Luke, Paul E.'),
    ('young sun (taiwan)', 'Young Sun (TAIWAN)'),
    ('texas marine international (usa)', 'Texas Marine International (USA)'),
    ('nacra catamarans', 'NACRA Catamarans'),
    ('performance catamarans inc.', 'Performance Catamarans Inc.'),
    ('cnb (fra)', 'CNB (FRA)'),
    ('merit marine inc.', 'Merit Marine Inc.'),
    ('multiplast', 'Multiplast'),
    ('sea nymph boats ltd. (nz)', 'Sea Nymph Boats Ltd. (NZ)'),
    ('construction navale franck roy', 'Construction Navale Franck Roy'),
    ('cleatline boats (usa)', 'Cleatline Boats (USA)'),
    ('bangor punta corp.', 'Bangor Punta Corp.'),
    ('la prairie (france)', 'La Prairie (FRANCE)'),
    ('lanaverre (fra)', 'Lanaverre (FRA)'),
    ('morgan-giles ltd.(uk)', 'Morgan-Giles Ltd.(UK)'),
    ('ott yacht (ger)', 'Ott Yacht (GER)'),
    ('frauscher boats', 'Frauscher Boats'),
    ('westsail corporation (usa)', 'Westsail Corporation (USA)'),
    ('olympic yachtcraft corp. (can)', 'Olympic Yachtcraft Corp. (CAN)'),
    ('the multihull center', 'The Multihull Center'),
    ('soca sailboats ltd.', 'SOCA Sailboats Ltd.'),
    ('lyman-morse', 'Lyman-Morse'),
    ('aegean yachtbuilders inc.', 'Aegean Yachtbuilders Inc.'),
    ('antares yachts', 'Antares Yachts'),
    ('bridges point boatyard', 'Bridges Point Boatyard'),
    ('rockport marine', 'Rockport Marine'),
    ('marstrom composite ab', 'Marstrom Composite AB'),
    ('mc-tec sarl (tun)', 'MC-TEC sarl (TUN)'),
    ('j.j. taylor and sons ltd. (can)', 'J.J. Taylor and Sons Ltd. (CAN)'),
    ('kanter yachts', 'Kanter Yachts'),
    ('goman boat ltd. (can)', 'Goman Boat Ltd. (CAN)'),
    ('vandestadt and mcgruer ltd. (can)', 'Vandestadt and McGruer Ltd. (CAN)'),
    ('winner yachts', 'Winner Yachts'),
    ('us yachts inc.', 'US Yachts Inc.'),
    ('hodgdon bros. (usa)', 'Hodgdon Bros. (USA)'),
    ('wellington boats inc.', 'Wellington Boats Inc.'),
    ('down east yachts inc.', 'Down East Yachts Inc.'),
    ('robertson and sons ltd.', 'Robertson and Sons Ltd.'),
    ('david heritage racing yachts', 'David Heritage Racing Yachts'),
    ('austral yachts', 'Austral Yachts'),
    ('kelt marine', 'Kelt Marine'),
    ('delphia yachts', 'Delphia Yachts'),
    ('wrighton yachts (fra)', 'Wrighton Yachts (FRA)'),
    ('walsteds baadevrft', 'Walsteds Baadevrft'),
    ('shipman', 'Shipman'),
    ('boston whaler (usa)', 'Boston Whaler (USA)'),
    ('endeavour yachts (aus)', 'Endeavour Yachts (AUS)'),
    ('hans christian yachts', 'Hans Christian Yachts'),
    ('swallow boats', 'Swallow Boats'),
    ('ax boats (esp)', 'AX Boats (ESP)'),
    ('jibetech (usa)', 'JIBETECH (USA)'),
    ('deger yachts (fin)', 'Deger Yachts (FIN)'),
    ('johannsen boat works', 'Johannsen Boat Works'),
    ('classic yachts inc. (usa)', 'Classic Yachts Inc. (USA)'),
    ('kang nam shipbuilders (kor)', 'Kang Nam Shipbuilders (KOR)'),
    ('reid marine (uk)', 'Reid Marine (UK)'),
    ('northwest yacht constructors ltd. (usa)', 'Northwest Yacht Constructors Ltd. (USA)'),
    ('nautitech catamarans (fra)', 'Nautitech Catamarans (FRA)'),
    ('jout (fra)', 'Jout (FRA)'),
    ('little harbor yachts', 'Little Harbor Yachts'),
    ('finn yachts ltd. (fi)', 'Finn Yachts Ltd. (FI)'),
    ('windward boatworks', 'Windward Boatworks'),
    ('barnett boats (usa)', 'Barnett Boats (USA)'),
    ('scanyacht ab', 'Scanyacht AB'),
    ('upham (uk) (j. w. and a. upham ltd.)', 'Upham (UK) (J. W. and A. Upham Ltd.)'),
    ('trident marine ltd. (uk)', 'Trident Marine Ltd. (UK)'),
    ('hartley boats', 'Hartley Boats'),
    ('xtreme sailing products', 'Xtreme Sailing Products'),
    ('motiva yachts', 'Motiva Yachts'),
    ('molich shipyard', 'Molich Shipyard'),
    ('fuji yacht builders ltd. (jap)', 'Fuji Yacht Builders Ltd. (JAP)'),
    ('windship yachts', 'Windship Yachts'),
    ('linjett boats (rosttra btvarv)', 'Linjett Boats (Rosttra Btvarv)'),
    ('dockrell yachts ltd.', 'Dockrell Yachts Ltd.'),
    ('rawson (ron rawson, inc.)', 'Rawson (Ron Rawson, Inc.)'),
    ('cape george marine works', 'Cape George Marine Works'),
    ('universal marine corp. (usa)', 'Universal Marine Corp. (USA)'),
    ('sailstar boat co. (usa)', 'Sailstar Boat Co. (USA)'),
    ('fiskars (fiskars ab )', 'Fiskars (Fiskars AB )'),
    ('mirage mfg. (usa)', 'Mirage Mfg. (USA)'),
    ('sears, roebuck & co.', 'Sears, Roebuck & Co.'),
    ('catana (fra)', 'Catana (FRA)'),
    ('offshore yachts ltd. (uk)', 'Offshore Yachts Ltd. (UK)'),
    ('glastron (usa)', 'Glastron (USA)'),
    ('ventilo srl (sui)', 'VENTILO Srl (SUI)'),
    ('maine cat', 'Maine Cat'),
    ('castlecraft', 'CastleCraft'),
    ('petticrows (uk)', 'Petticrows (UK)'),
    ('lm glasfiber', 'LM Glasfiber'),
    ('lear siegler inc.', 'Lear Siegler Inc.'),
    ('robert e. derecktor inc.', 'Robert E. Derecktor Inc.'),
    ('pyramid boat works', 'Pyramid Boat Works'),
    ('victoire yachts (nl)', 'Victoire Yachts (NL)'),
    ('henry r. mccune, shipbuilders', 'Henry R. McCune, Shipbuilders'),
    ('amf corp.', 'AMF Corp.'),
    ('cobra yachts (uk)', 'Cobra Yachts (UK)'),
    ('artekno oy (fin)', 'Artekno OY (FIN)'),
    ('polysier sa (esp)', 'Polysier SA (ESP)'),
    ('pointer yachts (uk)', 'Pointer Yachts (UK)'),
    ('newbridge boats ltd. (uk)', 'Newbridge Boats Ltd. (UK)'),
    ('compromis', 'Compromis'),
    ('american sail inc, (usa)', 'American Sail Inc, (USA)'),
    ('cornish crabbers', 'Cornish Crabbers'),
    ('sam l. morse co. (usa)', 'Sam L. Morse Co. (USA)'),
    ('e yacht builders (usa)', 'E Yacht Builders (USA)'),
    ('alajuela yacht corp.', 'Alajuela Yacht Corp.'),
    ('nimble boats works inc. (usa)', 'Nimble Boats Works Inc. (USA)'),
    ('union river boat co. (usa)', 'Union River Boat Co. (USA)'),
    ('performance sailcraft - ps2000', 'Performance Sailcraft - PS2000'),
    ('lockley newport boats (usa)', 'Lockley Newport Boats (USA)'),
    ('swarbrick & swarbrick', 'Swarbrick & Swarbrick'),
    ('edel catamarans (fra)', 'Edel Catamarans (FRA)'),
    ('pan oceanic marine.', 'Pan Oceanic Marine.'),
    ('dean catamarans (sa)', 'Dean Catamarans (SA)'),
    ('broadblue catamarans', 'Broadblue Catamarans'),
    ('schuchter sportboot', 'Schuchter Sportboot'),
    ('gunboat', 'Gunboat'),
    ('fyne boat kits (uk)', 'Fyne Boat Kits (UK)'),
    ('standfast yachts', 'Standfast Yachts'),
    ('shing fa boatbuilding co., ltd.', 'Shing Fa Boatbuilding Co., Ltd.'),
    ('artisan boatworks', 'Artisan Boatworks'),
    ('waarschip werft', 'Waarschip Werft'),
    ('boston boat works', 'Boston Boat works'),
    ('pert lowell co.', 'Pert Lowell Co.'),
    ('spirit yachts (uk)', 'Spirit Yachts (UK)'),
    ('exe fibercraft ltd. (can)', 'Exe Fibercraft Ltd. (CAN)'),
    ('halman manufacturing co.', 'Halman Manufacturing Co.'),
    ('evolution yachts ltd. (uk)', 'Evolution Yachts Ltd. (UK)'),
    ('palmer johnson (usa)', 'Palmer Johnson (USA)'),
    ('arcona yachts (boo marine)', 'Arcona Yachts (Boo Marine)'),
    ('kadley krogen yachts', 'Kadley Krogen Yachts'),
    ('advance sailboat corp. (usa)', 'Advance Sailboat Corp. (USA)'),
    ('summit yachts', 'Summit Yachts'),
    ('bossoms boatyard', 'Bossoms Boatyard'),
    ('cl sailboats', 'CL Sailboats'),
    ("arey's pond boatyard", "Arey's Pond Boatyard"),
    ('rob legg yachts ltd.', 'Rob Legg Yachts Ltd.'),
    ('lion yacht (lat)', 'Lion Yacht (LAT)'),
    ('glander boats inc. (usa)', 'Glander Boats Inc. (USA)'),
    ('gouteron (chantier) (fra)', 'Gouteron (Chantier) (FRA)'),
    ('oceanlake marine', 'Oceanlake Marine'),
    ('wally yachts', 'Wally Yachts'),
    ('saturn yachts ltd. (uk)', 'Saturn Yachts Ltd. (UK)'),
    ('metalmast marine', 'Metalmast Marine'),
    ('concordia company (usa)', 'Concordia Company (USA)'),
    ('snapir sailing craft ltd.', 'Snapir Sailing Craft Ltd.'),
    ('maxi yachts (swe)', 'Maxi Yachts (SWE)'),
    ('pacer yachts - south africa', 'Pacer Yachts - South Africa'),
    ('nash industries (can)', 'Nash Industries (CAN)'),
    ('windrush yachts (aus)', 'Windrush Yachts (AUS)'),
    ('iw-varvet (swe)', 'IW-Varvet (SWE)'),
    ('swanson brothers (aus)', 'Swanson Brothers (AUS)'),
    ('shumway marine (usa)', 'Shumway Marine (USA)'),
    ('jakobstads btvarv', 'Jakobstads Btvarv'),
    ('honnor marine ltd.', 'Honnor Marine Ltd.'),
    ('trump yachts', 'Trump Yachts'),
    ('dupuy chautard (fra)', 'Dupuy Chautard (FRA)'),
    ('edey & duff (usa)', 'Edey & Duff (USA)'),
    ('robertson & caine', 'Robertson & Caine'),
    ('cookson boats (nz)', 'Cookson Boats (NZ)'),
    ('norstar yachts inc. (usa)', 'Norstar Yachts Inc. (USA)'),
    ('jg marine', 'JG Marine'),
    ('nordship yachts aps', 'Nordship Yachts ApS'),
    ("philbrook's boatyard (can)", "Philbrook's Boatyard (CAN)"),
    ('northern yacht ltd. (can)', 'Northern Yacht Ltd. (CAN)'),
    ('kungsrs btvarv ab', 'Kungsrs Btvarv AB'),
    ('goodwood boat co. (uk)', 'GoodWood Boat Co. (UK)'),
    ('marten yachts', 'Marten Yachts'),
    ("cantieri navali d'este", "Cantieri Navali D'Este"),
    ('waterline systems, llc', 'Waterline Systems, LLC'),
    ('dk yachts', 'dk Yachts'),
    ('fantasi yachts (swe)', 'Fantasi Yachts (SWE)'),
    ('allures yachting (fra)', 'Allures Yachting (FRA)'),
    ('mg marine (usa)', 'MG Marine (USA)'),
    ('rice brothers (usa)', 'Rice Brothers (USA)'),
    ('kells corp. (usa)', 'Kells Corp. (USA)'),
    ('beetle boat co.', 'Beetle Boat Co.'),
    ('stebbings & sons (uk)', 'Stebbings & Sons (UK)'),
    ('far east yachts (jap)', 'Far East Yachts (JAP)'),
    ('lord nelson yachts', 'Lord Nelson Yachts'),
    ('pheon yachts ltd. (uk)', 'Pheon Yachts Ltd. (UK)'),
    ('jachtwerf gebr. de kloet bv', 'Jachtwerf Gebr. De Kloet BV'),
    ('mariner yacht co. (usa)', 'Mariner Yacht Co. (USA)'),
    ('gmach & co. ltd. (j. l. gmach & co.)', 'Gmach & Co. Ltd. (J. L. Gmach & Co.)'),
    ('winner boats s. l. (esp)', 'Winner Boats S. L. (ESP)'),
    ('nautivela (ita)', 'Nautivela (ITA)'),
    ('rydgeway marine ltd', 'Rydgeway Marine Ltd'),
    ('chung hwa boat (taiwan)', 'Chung Hwa Boat (TAIWAN)'),
    ('furia yachts (dresport)(esp)', 'Furia Yachts (DRESPORT)(ESP)'),
    ('binks yacht contructions', 'Binks Yacht Contructions'),
    ('classic boat shop', 'Classic Boat Shop'),
    ('chaisson boat builders (usa)', 'Chaisson Boat Builders (USA)'),
    ('huisman (royal huisman shipyard)', 'Huisman (Royal Huisman Shipyard)'),
    ('independent yachts ltd.', 'Independent Yachts Ltd.'),
    ('victoria yachts co.', 'Victoria Yachts Co.'),
    ('cenit', 'Cenit'),
    ('salona yachts (ad boats ltd.)', 'Salona Yachts (AD Boats Ltd.)'),
    ('formosa boat building co. ltd.', 'Formosa Boat Building Co. Ltd.'),
    ('g-cat multihulls', 'G-Cat Multihulls'),
    ('storebro bruk ab (swe)', 'Storebro Bruk AB (SWE)'),
    ('xiamen hansheng yacht building co. ltd.', 'Xiamen Hansheng Yacht Building Co. Ltd.'),
    ('prairie boat works (usa)', 'Prairie Boat Works (USA)'),
    ('easterly yachts (usa)', 'Easterly Yachts (USA)'),
    ('kaiser yachts', 'Kaiser Yachts'),
    ('bauteck marine (usa)', 'Bauteck Marine (USA)'),
    ("ballentines's boat shop (usa)", "Ballentines's Boat Shop (USA)"),
    ('prindle catamarans', 'Prindle Catamarans'),
    ('escape sailboat co.', 'Escape Sailboat Co.'),
    ('far east boat co.', 'Far East Boat Co.'),
    ('discovery yachts', 'Discovery Yachts'),
    ('menger boatworks (usa)', 'Menger Boatworks (USA)'),
    ('lagoon catamaran', 'Lagoon Catamaran'),
    ('costantini (chantier naval costantini)', 'Costantini (Chantier Naval Costantini)'),
    ('mcconaghy boats', 'McConaghy Boats'),
    ('fillip manufacturing co. (usa)', 'Fillip Manufacturing Co. (USA)'),
    ('customflex (usa)', 'Customflex (USA)'),
    ('pleasant bay boat & spar co.', 'Pleasant Bay Boat & Spar Co.'),
    ('rm yachts (fra)', 'RM Yachts (FRA)'),
    ('chantier jezequel', 'Chantier Jezequel'),
    ('winder boats (uk)', 'Winder Boats (UK)'),
    ('jp boats (uk)', 'JP Boats (UK)'),
    ('howard boats', 'Howard Boats'),
    ('lbi (usa)', 'LBI (USA)'),
    ('stroudwater boatworks', 'Stroudwater Boatworks'),
    ("durbeck's inc. (usa)", "Durbeck's Inc. (USA)"),
    ('projektowanie i budowa jachtw', 'Projektowanie i Budowa Jachtw'),
    ('breehorn (nl)', 'Breehorn (NL)'),
    ('rs sailing', 'RS Sailing'),
    ('phileas boats (fra)', 'Phileas Boats (FRA)'),
    ('hutting yachts (nl)', 'Hutting Yachts (NL)'),
    ('martin yachts ltd. (can)', 'Martin Yachts Ltd. (CAN)'),
    ('compass classic model sailing yachts', 'Compass Classic Model Sailing Yachts'),
    ('ithaca yachts', 'Ithaca Yachts'),
    ('landamores yacht builders (uk)', 'Landamores Yacht Builders (UK)'),
    ('new japan yacht co. ltd.', 'New Japan Yacht Co. Ltd.'),
    ('bruckmann yachts (can)', 'Bruckmann Yachts (CAN)'),
    ('atlanta bootsbau (ger)', 'Atlanta Bootsbau (GER)'),
    ('tomcat boats (can)', 'TomCat Boats (CAN)'),
    ('formula sailcraft', 'Formula Sailcraft'),
    ('heritage yacht corp. (usa)', 'Heritage Yacht Corp. (USA)'),
    ('excel yachts of sweden', 'Excel Yachts of Sweden'),
    ('beckerbt ab (swe)', 'Beckerbt AB (SWE)'),
    ('north sea craft (samphire)', 'North Sea Craft (Samphire)'),
    ('tournier marine (fra)', 'Tournier Marine (FRA)'),
    ('solaris yachts (italy)', 'Solaris Yachts (Italy)'),
    ('devoti sailing', 'Devoti Sailing'),
    ('dekleer brothers industries ltd.', 'Dekleer Brothers Industries Ltd.'),
    ('t-yachts (ita)', 'T-Yachts (ITA)'),
    ('wegu (ger/can)', 'Wegu (GER/CAN)'),
    ('burger boat company (usa)', 'Burger Boat Company (USA)'),
    ('outbound yachts', 'Outbound Yachts'),
    ('able marine (usa)', 'Able Marine (USA)'),
    ('seawind catamarans (aus)', 'Seawind Catamarans (AUS)'),
    ('skene boats ltd. (can)', 'Skene Boats Ltd. (CAN)'),
    ('b2 marine (fra)', 'B2 Marine (FRA)'),
    ('salthouse boatbuilders (nz)', 'Salthouse Boatbuilders (NZ)'),
    ('ggeri a/s', 'ggeri A/S'),
    ('blue jacket yachts', 'Blue Jacket Yachts'),
    ('friendship yachts (nl)', 'Friendship Yachts (NL)'),
    ('chris somner dinghy services (uk)', 'Chris Somner Dinghy Services (UK)'),
    ('stiletto catamarans (force engineering)', 'Stiletto Catamarans (Force Engineering)'),
    ('moore sailboats', 'Moore Sailboats'),
    ('olea composite (fra)', 'Olea Composite (FRA)'),
    ('copeland boats (uk)', 'Copeland Boats (UK)'),
    ('weta marine', 'Weta Marine'),
    ('astilleros pandora s.a. (ar)', 'Astilleros Pandora S.A. (AR)'),
    ('serius-werft', 'Serius-Werft'),
    ('dinghy sports', 'Dinghy Sports'),
    ('granada yachts (den)', 'Granada Yachts (DEN)'),
    ('snark sailboats (meyers boat co.)', 'Snark Sailboats (Meyers Boat Co.)'),
    ('saffier yachts', 'Saffier Yachts'),
    ('boreal (fra)', 'Boreal (FRA)'),
    ('pantawee marine co., ltd.', 'Pantawee Marine Co., Ltd.'),
    ('kolibri jachtbouw', 'Kolibri Jachtbouw'),
    ('open sailing inc. (usa)', 'Open Sailing Inc. (USA)'),
    ('laserperformance', 'LaserPerformance'),
    ('jpk composites', 'JPK Composites'),
    ('richmond marine ltd.', 'Richmond Marine Ltd.'),
    ('lindenberg yachts', 'Lindenberg Yachts'),
    ('starwind (usa)', 'Starwind (USA)'),
    ('butler mouldings ltd. (uk)', 'Butler Mouldings Ltd. (UK)'),
    ('bluboats', 'Bluboats'),
    ('bravura yachts inc.', 'Bravura Yachts Inc.'),
    ('admiralty yachts', 'Admiralty Yachts'),
    ('silverline boats (usa)', 'Silverline Boats (USA)'),
    ('turner marine (usa)', 'Turner Marine (USA)'),
    ('thompson boatworks', 'Thompson Boatworks'),
    ('alerion yachts (usa)', 'Alerion Yachts (USA)'),
    ('tes sailboats (poland)', 'Tes Sailboats (POLAND)'),
    ('sol catamarans (usa)', 'Sol Catamarans (USA)'),
    ('vander craft (uk)', 'Vander Craft (UK)'),
    ('cirrus raceboats ltd. (uk)', 'Cirrus Raceboats Ltd. (UK)'),
    ('salt marine inc. (usa)', 'Salt Marine Inc. (USA)'),
    ('maxi dolphin boatyard (ita)', 'Maxi Dolphin Boatyard (ITA)'),
    ('robinhood marine center', 'Robinhood Marine Center'),
    ('australian high performance catamarans', 'Australian High Performance Catamarans'),
    ('sage marine (usa)', 'Sage Marine (USA)'),
    ('penryn boatbuilding co. (uk)', 'Penryn Boatbuilding Co. (UK)'),
    ('multido (fra)', 'Multido (FRA)'),
    ('g-force yachts', 'G-Force Yachts'),
    ('seascape (slov)', 'Seascape (SLOV)'),
    ('m.a.t. sailing yachts', 'M.A.T. Sailing Yachts'),
    ('saphire ag', 'Saphire AG'),
    ('southern ocean shipyard ltd. (uk)', 'Southern Ocean Shipyard Ltd. (UK)'),
    ('windrider sailing trimarans', 'Windrider Sailing Trimarans'),
    ('leonardo yachts (nl)', 'Leonardo Yachts (NL)'),
    ('nebe boatworks (south africa)', 'Nebe Boatworks (South Africa)'),
    ('advanced yachts (ita)', 'Advanced Yachts (ITA)'),
    ('vico yachts ltd.', 'Vico Yachts Ltd.'),
    ('rinaldi (cantiere rinaldi)', 'Rinaldi (Cantiere Rinaldi)'),
    ('eagle marine (fin)', 'Eagle Marine (FIN)'),
    ('spirit yacht (belgium)', 'Spirit Yacht (Belgium)'),
    ('skaneateles boat & canoe co.', 'Skaneateles Boat & Canoe Co.'),
    ('penn yan boat company', 'Penn Yan Boat Company'),
    ('viksund (nor)', 'Viksund (NOR)'),
    ('dekker & sons (jachtwerf f. dekker en zonen)', 'Dekker & Sons (Jachtwerf F. Dekker en Zonen)'),
    ('howmar boats inc.', 'Howmar Boats Inc.'),
    ('wilderness boat works', 'Wilderness Boat Works'),
    ('tidewater boats (usa)', 'Tidewater Boats (USA)'),
    ('captiva yachts (usa)', 'Captiva Yachts (USA)'),
    ('naval force 3 (fra)', 'Naval Force 3 (FRA)'),
    ('koma boats ltd. (can)', 'Koma Boats Ltd. (CAN)'),
    ('stephens bros. boat builders', 'Stephens Bros. Boat Builders'),
    ('mobjack manufacturing corp.', 'Mobjack Manufacturing Corp.'),
    ('gibbs boat co. (usa)', 'Gibbs Boat Co. (USA)'),
    ('hutton yachts (australia)', 'Hutton Yachts (AUSTRALIA)'),
    ('bombardier ltd. (can)', 'Bombardier Ltd. (CAN)'),
    ('chippendale boats (uk)', 'Chippendale Boats (UK)'),
    ('j composites (fra)', 'J Composites (FRA)'),
    ('blue water yacht builders ltd. (taiwan)', 'Blue Water Yacht Builders Ltd. (TAIWAN)'),
    ('multihulls direct corp.', 'MultiHulls Direct Corp.'),
    ('hunboat (hu)', 'Hunboat (HU)'),
    ('albatros boats (ger)', 'Albatros Boats (GER)'),
    ('aztec yachts (can)', 'Aztec Yachts (CAN)'),
    ('mariner construes nuticas ltd. (bra)', 'Mariner Construes Nuticas Ltd. (BRA)'),
    ('sly yachts (ita)', 'Sly Yachts (ITA)'),
    ('nautivela shipyard (arg)', 'Nautivela Shipyard (ARG)'),
    ('vismara marine (ita)', 'Vismara Marine (ITA)'),
    ('balaton boats (hun)', 'Balaton Boats (HUN)'),
    ('fisher yachts international (uk)', 'Fisher Yachts International (UK)'),
    ('plasto gmbh & co.', 'Plasto GmbH & Co.'),
    ('blanchard boat co. (usa)', 'Blanchard Boat Co. (USA)'),
    ('sound boatbuilders (usa)', 'Sound Boatbuilders (USA)'),
    ('zygal boats (uk)', 'Zygal Boats (UK)'),
    ('hotfoot boats (can)', 'Hotfoot Boats (CAN)'),
    ('fiberglas technik (ger)', 'Fiberglas Technik (GER)'),
    ('gade marine (ger)', 'Gade Marine (GER)'),
    ('weathermark sailboats', 'Weathermark Sailboats'),
    ('pendleton yacht yard, inc.', 'Pendleton Yacht Yard, Inc.'),
    ('mao ta shipyard (taiwan)', 'Mao Ta Shipyard (TAIWAN)'),
    ('ho hsing f.r.p. co. ltd., (taiwan)', 'Ho Hsing F.R.P. Co. Ltd., (TAIWAN)'),
    ('kha shing enterprise co. ltd.', 'Kha Shing Enterprise Co. Ltd.'),
    ('w raceboats', 'W Raceboats'),
    ('gallart shipyard (astilleros gallart)', 'Gallart Shipyard (Astilleros Gallart)'),
    ('siddons & sindle (usa)', 'Siddons & Sindle (USA)'),
    ('pauger carbon ltd.', 'Pauger Carbon Ltd.'),
    ('proteus yachts (ita)', 'Proteus Yachts (ITA)'),
    ('premier composite technologies', 'Premier Composite Technologies'),
    ('mboats international (nor)', 'Mboats International (NOR)'),
    ('krona boats (swe)', 'Krona Boats (SWE)'),
    ('betts moulding ltd.', 'Betts Moulding Ltd.'),
    ('triaksports', 'TRiAKsports'),
    ('aventura catamarans', 'Aventura Catamarans'),
    ('dromor yachts', 'Dromor Yachts'),
    ('sirius -werft gmbh', 'Sirius -Werft GmbH'),
    ('lien hwa industrial corp.', 'Lien Hwa Industrial Corp.'),
    ('evanson (p.) boat co. (usa)', 'Evanson (P.) Boat Co. (USA)'),
    ('challenger yachts ltd.(can)', 'Challenger Yachts Ltd.(CAN)'),
    ('birka marine (fin)', 'Birka Marine (FIN)'),
    ('southport island marine (usa)', 'Southport Island Marine (USA)'),
    ('left coast development', 'Left Coast Development'),
    ('fisher motor sailers', 'Fisher Motor Sailers'),
    ('neo yachts', 'Neo Yachts'),
    ('mylius yachts (ita)', 'Mylius Yachts (ITA)'),
    ('m boats (arg)', 'M Boats (ARG)'),
    ('martinoli marine', 'Martinoli Marine')
)

CHOICES_BUILDING_MATERIAL = (
    ('other', 'Other'),
    ('fiber_glass', 'Fiber glass (polyester)'),
    ('steel', 'Steel'),
    ('aluminium', 'Aluminium'),
    ('composite', '(Epoxy) composite'),
    ('wood', 'Wood'),
    ('woodcore', 'Woodcore'),
)

CHOICES_ENGINE_NAME = (
    ('other', 'Other'),
    ('yanmar', 'Yanmar'),
    ('volvo', 'Volvo'),
    ('albin', 'Albin'),
    ('ford', 'Ford'),
    ('perkins', 'Perkins'),
    ('lombardini', 'Lombardini'),
    ('caterpillar', 'Caterpillar'),
)

CHOICES_STEERING = (
    ('other', 'Other'),
    ('wheel', 'Wheel(s)'),
    ('tiller', 'Tiller (helm)'),
)
